setGeneric("QCData",    function(object) standardGeneric("QCData"))
setGeneric("threshold", function(object) standardGeneric("threshold"))
setGeneric("windowsize",function(object) standardGeneric("windowsize"))
setGeneric("Position",  function(object) standardGeneric("Position"))
setGeneric("Chromosome",function(object) standardGeneric("Chromosome"))
setGeneric("vals",      function(object) standardGeneric("vals"))
setGeneric("pvals",     function(object) standardGeneric("pvals"))
setGeneric("Pos",     function(object) standardGeneric("Pos"))
